In [1]:
import pandas as pd
import numpy as np

#importing the csv files
train_data=pd.read_csv('train.csv')
test_data=pd.read_csv('test.csv')

titanic_data= pd.read_csv('TitanicData-csv.csv')
titanic_data

PassengerId  Survived  Pclass  \
0               1       0.0       3   
1               2       1.0       1   
2               3       1.0       3   
3               4       1.0       1   
4               5       0.0       3   
...           ...       ...     ...   
1304         1305       NaN       3   
1305         1306       NaN       1   
1306         1307       NaN       3   
1307         1308       NaN       3   
1308         1309       NaN       3   

                                                   Name     Sex   Age  SibSp  \
0                               Braund, Mr. Owen Harris    male  22.0      1   
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                                Heikkinen, Miss. Laina  female  26.0      0   
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                              Allen, Mr. William Henry    male  35.0      0   
...                                                 ...     ...   ...    ...   
1304                                 Spector, Mr. Woolf    male  23.0      0   
1305                       Oliva y Ocana, Dona. Fermina  female  39.0      0   
1306                       Saether, Mr. Simon Sivertsen    male  38.5      0   
1307                                Ware, Mr. Frederick    male  35.0      0   
1308                           Peter, Master. Michael J    male   NaN      1   

      Parch Embarked  
0         0        S  
1         0        C  
2         0        S  
3         0        S  
4         0        S  
...     ...      ...  
1304      0        S  
1305      0        C  
1306      0        S  
1307      0        S  
1308      1        C  

[1309 rows x 9 columns]

In [2]:
#Performing data cleaning

titanic_data=titanic_data.drop(['PassengerId','Name'],axis=1)
titanic_data['Sex']=titanic_data['Sex'].replace(to_replace=['male','female'], value=[1,0])
titanic_data['Age']=titanic_data['Age'].fillna(titanic_data['Age'].mean())
titanic_data['Survived']=titanic_data['Survived'].replace(to_replace=np.nan, value=-1)
titanic_data['Survived']=titanic_data['Survived'].astype(int)
titanic_data['Embarked']=titanic_data['Embarked'].replace(to_replace=['S','Q','C'], value=[3,2,1])
titanic_data

Survived  Pclass  Sex        Age  SibSp  Parch  Embarked
0            0       3    1  22.000000      1      0         3
1            1       1    0  38.000000      1      0         1
2            1       3    0  26.000000      0      0         3
3            1       1    0  35.000000      1      0         3
4            0       3    1  35.000000      0      0         3
...        ...     ...  ...        ...    ...    ...       ...
1304        -1       3    1  23.000000      0      0         3
1305        -1       1    0  39.000000      0      0         1
1306        -1       3    1  38.500000      0      0         3
1307        -1       3    1  35.000000      0      0         3
1308        -1       3    1  29.774419      1      1         1

[1309 rows x 7 columns]

In [3]:
for x in titanic_data['Age']:
    if (x>0.0) & (x<=17.0):
        titanic_data['Age']=titanic_data['Age'].replace(to_replace=x,value='child') # 1= child
    elif (x>17.0) & (x<=35.0):
        titanic_data['Age']=titanic_data['Age'].replace(to_replace=x,value='young adult') # 2= young adult
    elif (x>35.0) & (x<=59):
        titanic_data['Age']=titanic_data['Age'].replace(to_replace=x,value='adult') # 3= adult
    else:
        titanic_data['Age']=titanic_data['Age'].replace(to_replace=x,value='senior citizen') # 4=senior citizen

titanic_data

Survived  Pclass  Sex          Age  SibSp  Parch  Embarked
0            0       3    1  young adult      1      0         3
1            1       1    0        adult      1      0         1
2            1       3    0  young adult      0      0         3
3            1       1    0  young adult      1      0         3
4            0       3    1  young adult      0      0         3
...        ...     ...  ...          ...    ...    ...       ...
1304        -1       3    1  young adult      0      0         3
1305        -1       1    0        adult      0      0         1
1306        -1       3    1        adult      0      0         3
1307        -1       3    1  young adult      0      0         3
1308        -1       3    1  young adult      1      1         1

[1309 rows x 7 columns]

In [4]:
titanic_data['Age']=titanic_data['Age'].replace(to_replace=['child','young adult','adult','senior citizen'],value=[1,2,3,4])
titanic_data

Survived  Pclass  Sex  Age  SibSp  Parch  Embarked
0            0       3    1    2      1      0         3
1            1       1    0    3      1      0         1
2            1       3    0    2      0      0         3
3            1       1    0    2      1      0         3
4            0       3    1    2      0      0         3
...        ...     ...  ...  ...    ...    ...       ...
1304        -1       3    1    2      0      0         3
1305        -1       1    0    3      0      0         1
1306        -1       3    1    3      0      0         3
1307        -1       3    1    2      0      0         3
1308        -1       3    1    2      1      1         1

[1309 rows x 7 columns]

In [5]:
# Then performing data Pre-processing
y=titanic_data.iloc[:,0].values
x=titanic_data.iloc[:,1:].values
x

array([[3, 1, 2, 1, 0, 3],
       [1, 0, 3, 1, 0, 1],
       [3, 0, 2, 0, 0, 3],
       ...,
       [3, 1, 3, 0, 0, 3],
       [3, 1, 2, 0, 0, 3],
       [3, 1, 2, 1, 1, 1]], dtype=int64)

In [6]:
x_train=x[:891]
y_train=y[:891]
x_test=x[891:]
y_test=y[891:]
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

array([[ 0.82737724,  0.73769513, -0.264414  ,  0.43279337, -0.47367361,
         0.58595414],
       [-1.56610693, -1.35557354,  1.14632179,  0.43279337, -0.47367361,
        -1.9423032 ],
       [ 0.82737724, -1.35557354, -0.264414  , -0.4745452 , -0.47367361,
         0.58595414],
       ...,
       [ 0.82737724, -1.35557354, -0.264414  ,  0.43279337,  2.00893337,
         0.58595414],
       [-1.56610693,  0.73769513, -0.264414  , -0.4745452 , -0.47367361,
        -1.9423032 ],
       [ 0.82737724,  0.73769513, -0.264414  , -0.4745452 , -0.47367361,
        -0.67817453]])

In [26]:
# Performing a Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

RF= RandomForestClassifier(n_estimators=100, max_depth=5, random_state=7)
estim= RF.fit(x_train,y_train)
estim

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=7, verbose=0,
                       warm_start=False)

In [28]:

from sklearn.model_selection import cross_val_score
score=cross_val_score(estim,x_train,y_train,cv=8)
score.mean()

0.8159387065637065

In [10]:
# now making predictions against the test data
y_predict=RF.predict(x_test)
y_predict

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [19]:
# creating a new dataframe for submittig the predictions to a kaggle competition project
predictions= pd.read_csv('test-csv.csv')
predictions.insert(1,'Survived',y_predict,True)
predictions.to_csv('RFPredictions.csv',index=False)
predictions

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]